// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_large

#ifndef UI_BOOTSCR_H
#define UI_BOOTSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BootScr
extern void ui_BootScr_screen_init(void);
extern void ui_BootScr_screen_destroy(void);
extern lv_obj_t * ui_BootScr;
extern lv_obj_t * ui_LblPrjName;
extern lv_obj_t * ui_LblVersion;
extern lv_obj_t * ui_LblConnection;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

