// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_large

#include "ui.h"

lv_obj_t * ui_BootScr = NULL;
lv_obj_t * ui_LblPrjName = NULL;
lv_obj_t * ui_LblVersion = NULL;
// event funtions
void ui_event_BootScr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenSolver(e);
    }
}

// build funtions

void ui_BootScr_screen_init(void)
{
    ui_BootScr = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BootScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblPrjName = lv_label_create(ui_BootScr);
    lv_obj_set_width(ui_LblPrjName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPrjName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPrjName, 0);
    lv_obj_set_y(ui_LblPrjName, -30);
    lv_obj_set_align(ui_LblPrjName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPrjName, "Web Radio");
    lv_obj_set_style_text_font(ui_LblPrjName, &ui_font_Roboto_Reg_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblVersion = lv_label_create(ui_BootScr);
    lv_obj_set_width(ui_LblVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblVersion, 0);
    lv_obj_set_y(ui_LblVersion, 90);
    lv_obj_set_align(ui_LblVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblVersion, "V 1.0.0");
    lv_obj_set_style_text_font(ui_LblVersion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BootScr, ui_event_BootScr, LV_EVENT_ALL, NULL);

}

void ui_BootScr_screen_destroy(void)
{
    if(ui_BootScr) lv_obj_del(ui_BootScr);

    // NULL screen variables
    ui_BootScr = NULL;
    ui_LblPrjName = NULL;
    ui_LblVersion = NULL;

}
