// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_large

#include "ui.h"

lv_obj_t * ui_ConnScr = NULL;
lv_obj_t * ui_LblbConnecting = NULL;
// event funtions

// build funtions

void ui_ConnScr_screen_init(void)
{
    ui_ConnScr = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConnScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblbConnecting = lv_label_create(ui_ConnScr);
    lv_obj_set_width(ui_LblbConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblbConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblbConnecting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblbConnecting, "Connecting to WiFi..");
    lv_obj_set_style_text_font(ui_LblbConnecting, &ui_font_Roboto_Reg_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ConnScr_screen_destroy(void)
{
    if(ui_ConnScr) lv_obj_del(ui_ConnScr);

    // NULL screen variables
    ui_ConnScr = NULL;
    ui_LblbConnecting = NULL;

}
