// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_large

#ifndef UI_WMSCRN_H
#define UI_WMSCRN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WmScrn
extern void ui_WmScrn_screen_init(void);
extern void ui_WmScrn_screen_destroy(void);
extern lv_obj_t * ui_WmScrn;
extern lv_obj_t * ui_LblNoConn;
extern lv_obj_t * ui_LbLRadioAP;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

