// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_large

#include "ui.h"

lv_obj_t * ui_WmScrn = NULL;
lv_obj_t * ui_LblNoConn = NULL;
lv_obj_t * ui_LbLRadioAP = NULL;
// event funtions

// build funtions

void ui_WmScrn_screen_init(void)
{
    ui_WmScrn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WmScrn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblNoConn = lv_label_create(ui_WmScrn);
    lv_obj_set_width(ui_LblNoConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNoConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblNoConn, 0);
    lv_obj_set_y(ui_LblNoConn, -90);
    lv_obj_set_align(ui_LblNoConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNoConn, "No saved WiFi connection.");
    lv_obj_set_style_text_font(ui_LblNoConn, &ui_font_Roboto_Reg_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbLRadioAP = lv_label_create(ui_WmScrn);
    lv_obj_set_width(ui_LbLRadioAP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbLRadioAP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbLRadioAP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbLRadioAP, "Connect to WebRadioAP\nand setup your WiFi credentials.");
    lv_obj_set_style_text_align(ui_LbLRadioAP, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbLRadioAP, &ui_font_Roboto_Reg_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_WmScrn_screen_destroy(void)
{
    if(ui_WmScrn) lv_obj_del(ui_WmScrn);

    // NULL screen variables
    ui_WmScrn = NULL;
    ui_LblNoConn = NULL;
    ui_LbLRadioAP = NULL;

}
