; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = large

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
framework = arduino
monitor_speed = 115200
lib_deps = 
	lvgl/lvgl
	moononournation/GFX Library for Arduino@^1.6.2
	TFT_eSPI
	ESP32-audioI2S-master=https://github.com/schreibfaul1/ESP32-audioI2S/archive/master.zip
	tzapu/WiFiManager
build_flags =
    -D CORE_DEBUG_LEVEL=3                    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ARDUINO_RUNNING_CORE=1                ; Arduino Runs On Core (setup, loop)
    -D AUDIOTASK_CORE=0                      ; 0 or 1 - reads from the InBuffer, decodes and feeds I2S
    -D BOARD_HAS_PSRAM=1 

[env:small]
build_flags = -Dsmall
	${env.build_flags}
src_filter = +<*> +<ui/small> -<ui/large>
lib_deps = 
	${env.lib_deps}

[env:large]
build_flags = -Dlarge
	${env.build_flags}

src_filter = +<*> +<ui/large> -<ui/small>
lib_deps = 
	${env.lib_deps} 
	
