; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; https://github.com/sivar2311/ESP32-PlatformIO-Flash-and-PSRAM-configurations

[platformio]
default_envs = small

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n4r2
board_build.mcu = esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_qspi ; qio_qspi for N4R2 / qio_opi for N4R8
board_build.flash_mode = qio
board_build.psram_type = qio ; qio for N4R2 / opi for N4R8
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = boards/huge_app.csv
monitor_filters = esp32_exception_decoder
lib_deps = 
	lvgl/lvgl
	moononournation/GFX Library for Arduino
	TFT_eSPI
	ESP32-audioI2S-master=https://github.com/schreibfaul1/ESP32-audioI2S/archive/master.zip
	tzapu/WiFiManager
	bblanchon/ArduinoJson
build_flags =
	-D CORE_DEBUG_LEVEL=1                    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ARDUINO_RUNNING_CORE=1                ; Arduino Runs On Core (setup, loop)
    -D AUDIOTASK_CORE=0                      ; 0 or 1 - reads from the InBuffer, decodes and feeds I2S
    -D BOARD_HAS_PSRAM=1
	-D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_USE_PERF_MONITOR=0				; if 1 LVGL will show FPS & CPU usage
	-D'LV_CONF_PATH="${PROJECT_DIR}/lib/lv_conf.h"'  

[env:small]
build_flags = -Dsmall
	${env.build_flags}
build_src_filter = +<*> +<ui/small> -<ui/large>
lib_deps = 
	${env.lib_deps}

[env:small_n4r2]
extends = env:small
board = esp32-s3-devkitc1-n4r2
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

[env:small_n4r8]
extends = env:small
board = esp32-s3-devkitc1-n4r8
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

[env:large]
build_flags = -Dlarge
	${env.build_flags}

build_src_filter = +<*> +<ui/large> -<ui/small>
lib_deps = 
	${env.lib_deps} 
	
