// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Web_radio

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_CntnrTime;
lv_obj_t * ui_LblHrs;
lv_obj_t * ui_LblMin;
lv_obj_t * ui_LblDots;
lv_obj_t * ui_LblDate;
lv_obj_t * ui_CntnrWeather;
lv_obj_t * ui_CntnrButtons;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Container5;
lv_obj_t * ui_CntnrRadio;
lv_obj_t * ui_LblStation;
lv_obj_t * ui_LblCurPlaying;
lv_obj_t * ui_PnlHorLine;
lv_obj_t * ui_PnlVerLine;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
