// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Web_radio

#ifndef _WEB_RADIO_UI_H
#define _WEB_RADIO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_CntnrTime;
extern lv_obj_t * ui_LblHrs;
extern lv_obj_t * ui_LblMin;
extern lv_obj_t * ui_LblDots;
extern lv_obj_t * ui_LblDate;
extern lv_obj_t * ui_CntnrWeather;
extern lv_obj_t * ui_CntnrRadio;
extern lv_obj_t * ui_CntnrVisualisation;
extern lv_obj_t * ui_LblStation;
extern lv_obj_t * ui_LblCurPlaying;
extern lv_obj_t * ui_CntnrButtons;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Container1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Container2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Container3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Container4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_PnlHorLine;
extern lv_obj_t * ui_PnlVerLine;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
