// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_small

#ifndef _WEB_RADIO_SMALL_UI_H
#define _WEB_RADIO_SMALL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////
#include "ui_ScrBoot.h"
#include "ui_ScrRadioPlayer.h"
#include "ui_ScrMusicPlayer.h"
#include "ui_ScrNetworkPlayer.h"
#include "ui_ScrWiFiManager.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * VolumeHide_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_music_player_logo_png);   // assets/music_player_logo.png
LV_IMG_DECLARE( ui_img_weather_icons_dovora_interactive_128px_day_clear_png);   // assets/weather_icons_dovora_interactive_128px/day_clear.png
LV_IMG_DECLARE( ui_img_weather_icons_dovora_interactive_128px_cloudy_png);   // assets/weather_icons_dovora_interactive_128px/cloudy.png
LV_IMG_DECLARE( ui_img_indicator_hor_small_png);   // assets/indicator_hor_small.png

// FONTS
LV_FONT_DECLARE( ui_font_Roboto_Reg_10);
LV_FONT_DECLARE( ui_font_Roboto_Reg_12);
LV_FONT_DECLARE( ui_font_Roboto_Reg_14);
LV_FONT_DECLARE( ui_font_Roboto_Reg_16);
LV_FONT_DECLARE( ui_font_Roboto_Reg_18);
LV_FONT_DECLARE( ui_font_Roboto_Reg_28);
LV_FONT_DECLARE( ui_font_Roboto_Reg_48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
