// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: Web_radio_small

#include "ui.h"

lv_obj_t * ui_ScrBoot = NULL;
lv_obj_t * ui_ImgLogo = NULL;
lv_obj_t * ui_LblInfo = NULL;
lv_obj_t * ui_LblVersion = NULL;
// event funtions

// build funtions

void ui_ScrBoot_screen_init(void)
{
    ui_ScrBoot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrBoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrBoot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrBoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgLogo = lv_image_create(ui_ScrBoot);
    lv_image_set_src(ui_ImgLogo, &ui_img_music_player_logo_png);
    lv_obj_set_width(ui_ImgLogo, 320);
    lv_obj_set_height(ui_ImgLogo, 240);
    lv_obj_set_x(ui_ImgLogo, 0);
    lv_obj_set_y(ui_ImgLogo, -30);
    lv_obj_set_align(ui_ImgLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblInfo = lv_label_create(ui_ScrBoot);
    lv_obj_set_width(ui_LblInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblInfo, 0);
    lv_obj_set_y(ui_LblInfo, 50);
    lv_obj_set_align(ui_LblInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblInfo, "info text");
    lv_obj_set_style_text_font(ui_LblInfo, &ui_font_Roboto_Reg_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblVersion = lv_label_create(ui_ScrBoot);
    lv_obj_set_width(ui_LblVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblVersion, 0);
    lv_obj_set_y(ui_LblVersion, 100);
    lv_obj_set_align(ui_LblVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblVersion, "fw version");
    lv_obj_set_style_text_font(ui_LblVersion, &ui_font_Roboto_Reg_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScrBoot_screen_destroy(void)
{
    if(ui_ScrBoot) lv_obj_del(ui_ScrBoot);

    // NULL screen variables
    ui_ScrBoot = NULL;
    ui_ImgLogo = NULL;
    ui_LblInfo = NULL;
    ui_LblVersion = NULL;

}
