// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_small

#ifndef UI_SCRMUSICPLAYER_H
#define UI_SCRMUSICPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_ScrMusicPlayer
extern void ui_ScrMusicPlayer_screen_init(void);
extern void ui_ScrMusicPlayer_screen_destroy(void);
extern lv_obj_t *ui_ScrMusicPlayer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

