// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Web_radio_small

#ifndef UI_SCRBOOT_H
#define UI_SCRBOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrBoot
extern void ui_ScrBoot_screen_init(void);
extern void ui_ScrBoot_screen_destroy(void);
extern lv_obj_t * ui_ScrBoot;
extern lv_obj_t * ui_ImgLogo;
extern lv_obj_t * ui_LblInfo;
extern lv_obj_t * ui_LblVersion;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

