// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_small

#ifndef UI_SCRWIFIMANAGER_H
#define UI_SCRWIFIMANAGER_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_ScrWiFiManager
extern void ui_ScrWiFiManager_screen_init(void);
extern void ui_ScrWiFiManager_screen_destroy(void);
extern lv_obj_t *ui_ScrWiFiManager;
extern lv_obj_t *ui_ScrWmLbl0;
extern lv_obj_t *ui_ScrWmLbl1;
extern lv_obj_t *ui_ScrWmLblAP;
extern lv_obj_t *ui_ScrWmLbl2;
extern lv_obj_t *ui_ScrWmLblAddress;
extern lv_obj_t *ui_ScrWmLbl3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

