// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Web_radio_small

#ifndef UI_SCRMUSICPLAYER_H
#define UI_SCRMUSICPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrMusicPlayer
extern void ui_ScrMusicPlayer_screen_init(void);
extern void ui_ScrMusicPlayer_screen_destroy(void);
extern lv_obj_t * ui_ScrMusicPlayer;
extern lv_obj_t * ui_CntnrButtonsPlayer;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_PnlHorLinePlayer;
extern lv_obj_t * ui_SliderPlayTime;
extern lv_obj_t * ui_LblCurPlayedTime;
extern lv_obj_t * ui_LblSongDuration;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CntnrButtonsPlayer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

