// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_small

#include "ui.h"

lv_obj_t *ui_ScrNetworkPlayer = NULL;
// event funtions

// build funtions

void ui_ScrNetworkPlayer_screen_init(void)
{
ui_ScrNetworkPlayer = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScrNetworkPlayer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_ScrNetworkPlayer_screen_destroy(void)
{
   if (ui_ScrNetworkPlayer) lv_obj_del(ui_ScrNetworkPlayer);

// NULL screen variables
ui_ScrNetworkPlayer= NULL;

}
