// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: Web_radio_small

#ifndef UI_SCRNETWORKPLAYER_H
#define UI_SCRNETWORKPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrNetworkPlayer
extern void ui_ScrNetworkPlayer_screen_init(void);
extern void ui_ScrNetworkPlayer_screen_destroy(void);
extern lv_obj_t * ui_ScrNetworkPlayer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

