// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Web_radio_small

#ifndef UI_SCRRADIOPLAYER_H
#define UI_SCRRADIOPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_ScrRadioPlayer
extern void ui_ScrRadioPlayer_screen_init(void);
extern void ui_ScrRadioPlayer_screen_destroy(void);
extern lv_obj_t *ui_ScrRadioPlayer;
extern lv_obj_t *ui_CntnrTime;
extern lv_obj_t *ui_LblHrs;
extern lv_obj_t *ui_LblMin;
extern lv_obj_t *ui_LblDots;
extern lv_obj_t *ui_LblDate;
extern lv_obj_t *ui_CntnrWeather;
extern lv_obj_t *ui_ImgDayClear;
extern lv_obj_t *ui_ImgCloudy;
extern lv_obj_t *ui_LblWeather;
extern lv_obj_t *ui_CntnrButtons;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_CntnrRadio;
extern lv_obj_t *ui_LblStation;
extern lv_obj_t *ui_LblCurPlaying;
extern lv_obj_t *ui_PnlHorLine;
extern lv_obj_t *ui_PnlVerLine;
extern lv_obj_t *ui_SldrVolume;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

