// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: Web_radio_small

#include "ui.h"

lv_obj_t * uic_CntnrButtonsPlayer;
lv_obj_t * ui_ScrMusicPlayer = NULL;
lv_obj_t * ui_CntnrButtonsPlayer = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_PnlHorLinePlayer = NULL;
lv_obj_t * ui_SliderPlayTime = NULL;
lv_obj_t * ui_LblCurPlayedTime = NULL;
lv_obj_t * ui_LblSongDuration = NULL;
// event funtions
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Image4, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Image4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Image3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_Image3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_ScrMusicPlayer_screen_init(void)
{
    ui_ScrMusicPlayer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrMusicPlayer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrMusicPlayer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMusicPlayer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CntnrButtonsPlayer = lv_obj_create(ui_ScrMusicPlayer);
    lv_obj_remove_style_all(ui_CntnrButtonsPlayer);
    lv_obj_set_height(ui_CntnrButtonsPlayer, 35);
    lv_obj_set_width(ui_CntnrButtonsPlayer, lv_pct(100));
    lv_obj_set_x(ui_CntnrButtonsPlayer, 0);
    lv_obj_set_y(ui_CntnrButtonsPlayer, -5);
    lv_obj_set_align(ui_CntnrButtonsPlayer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_CntnrButtonsPlayer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_button_create(ui_CntnrButtonsPlayer);
    lv_obj_set_height(ui_Button14, 30);
    lv_obj_set_width(ui_Button14, lv_pct(15));
    lv_obj_set_x(ui_Button14, -120);
    lv_obj_set_y(ui_Button14, 0);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button14, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button14, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image6 = lv_image_create(ui_Button14);
    lv_image_set_src(ui_Image6, &ui_img_194650559);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor_opa(ui_Image6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button9 = lv_button_create(ui_CntnrButtonsPlayer);
    lv_obj_set_height(ui_Button9, 30);
    lv_obj_set_width(ui_Button9, lv_pct(15));
    lv_obj_set_x(ui_Button9, -60);
    lv_obj_set_y(ui_Button9, 0);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image4 = lv_image_create(ui_Button9);
    lv_image_set_src(ui_Image4, &ui_img_backward_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image4, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button10 = lv_button_create(ui_CntnrButtonsPlayer);
    lv_obj_set_height(ui_Button10, 30);
    lv_obj_set_width(ui_Button10, lv_pct(15));
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button10, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button10, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image1 = lv_image_create(ui_Button10);
    lv_image_set_src(ui_Image1, &ui_img_pause_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 200);

    ui_Image2 = lv_image_create(ui_Button10);
    lv_image_set_src(ui_Image2, &ui_img_play_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 13
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button11 = lv_button_create(ui_CntnrButtonsPlayer);
    lv_obj_set_height(ui_Button11, 30);
    lv_obj_set_width(ui_Button11, lv_pct(15));
    lv_obj_set_x(ui_Button11, 60);
    lv_obj_set_y(ui_Button11, 0);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button11, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image3 = lv_image_create(ui_Button11);
    lv_image_set_src(ui_Image3, &ui_img_forward_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image3, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor_opa(ui_Image3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button12 = lv_button_create(ui_CntnrButtonsPlayer);
    lv_obj_set_height(ui_Button12, 30);
    lv_obj_set_width(ui_Button12, lv_pct(15));
    lv_obj_set_x(ui_Button12, 120);
    lv_obj_set_y(ui_Button12, 0);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button12, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image5 = lv_image_create(ui_Button12);
    lv_image_set_src(ui_Image5, &ui_img_194652857);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_image_recolor_opa(ui_Image5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PnlHorLinePlayer = lv_obj_create(ui_ScrMusicPlayer);
    lv_obj_set_height(ui_PnlHorLinePlayer, 2);
    lv_obj_set_width(ui_PnlHorLinePlayer, lv_pct(90));
    lv_obj_set_x(ui_PnlHorLinePlayer, 0);
    lv_obj_set_y(ui_PnlHorLinePlayer, -95);
    lv_obj_set_align(ui_PnlHorLinePlayer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PnlHorLinePlayer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlHorLinePlayer, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlHorLinePlayer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPlayTime = lv_slider_create(ui_ScrMusicPlayer);
    lv_slider_set_value(ui_SliderPlayTime, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPlayTime) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_SliderPlayTime, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderPlayTime, 10);
    lv_obj_set_width(ui_SliderPlayTime, lv_pct(60));
    lv_obj_set_x(ui_SliderPlayTime, 0);
    lv_obj_set_y(ui_SliderPlayTime, 55);
    lv_obj_set_align(ui_SliderPlayTime, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderPlayTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPlayTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPlayTime, lv_color_hex(0x545558), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPlayTime, 64, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPlayTime, lv_color_hex(0x353535), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPlayTime, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderPlayTime, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderPlayTime, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderPlayTime, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderPlayTime, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderPlayTime, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderPlayTime,
                                                                                                     lv_obj_get_style_pad_right(ui_SliderPlayTime, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LblCurPlayedTime = lv_label_create(ui_ScrMusicPlayer);
    lv_obj_set_width(ui_LblCurPlayedTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCurPlayedTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblCurPlayedTime, -130);
    lv_obj_set_y(ui_LblCurPlayedTime, 55);
    lv_obj_set_align(ui_LblCurPlayedTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCurPlayedTime, "text");
    lv_obj_set_style_text_font(ui_LblCurPlayedTime, &ui_font_Roboto_Reg_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSongDuration = lv_label_create(ui_ScrMusicPlayer);
    lv_obj_set_width(ui_LblSongDuration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSongDuration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSongDuration, 130);
    lv_obj_set_y(ui_LblSongDuration, 55);
    lv_obj_set_align(ui_LblSongDuration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSongDuration, "text");
    lv_obj_set_style_text_font(ui_LblSongDuration, &ui_font_Roboto_Reg_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    uic_CntnrButtonsPlayer = ui_CntnrButtonsPlayer;

}

void ui_ScrMusicPlayer_screen_destroy(void)
{
    if(ui_ScrMusicPlayer) lv_obj_del(ui_ScrMusicPlayer);

    // NULL screen variables
    ui_ScrMusicPlayer = NULL;
    uic_CntnrButtonsPlayer = NULL;
    ui_CntnrButtonsPlayer = NULL;
    ui_Button14 = NULL;
    ui_Image6 = NULL;
    ui_Button9 = NULL;
    ui_Image4 = NULL;
    ui_Button10 = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Button11 = NULL;
    ui_Image3 = NULL;
    ui_Button12 = NULL;
    ui_Image5 = NULL;
    ui_PnlHorLinePlayer = NULL;
    ui_SliderPlayTime = NULL;
    ui_LblCurPlayedTime = NULL;
    ui_LblSongDuration = NULL;

}
