// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Web_radio_small

#include "ui.h"

lv_obj_t * ui_ScrWiFiManager = NULL;
lv_obj_t * ui_ScrWmLbl0 = NULL;
lv_obj_t * ui_ScrWmLbl1 = NULL;
lv_obj_t * ui_ScrWmLblAP = NULL;
lv_obj_t * ui_ScrWmLbl2 = NULL;
lv_obj_t * ui_ScrWmLblAddress = NULL;
lv_obj_t * ui_ScrWmLbl3 = NULL;
// event funtions

// build funtions

void ui_ScrWiFiManager_screen_init(void)
{
    ui_ScrWiFiManager = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrWiFiManager, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrWiFiManager, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWiFiManager, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWmLbl0 = lv_label_create(ui_ScrWiFiManager);
    lv_obj_set_width(ui_ScrWmLbl0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWmLbl0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrWmLbl0, 0);
    lv_obj_set_y(ui_ScrWmLbl0, -100);
    lv_obj_set_align(ui_ScrWmLbl0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWmLbl0, "No WiFi connection was found. ");
    lv_obj_set_style_text_font(ui_ScrWmLbl0, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWmLbl1 = lv_label_create(ui_ScrWiFiManager);
    lv_obj_set_width(ui_ScrWmLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWmLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrWmLbl1, 0);
    lv_obj_set_y(ui_ScrWmLbl1, -65);
    lv_obj_set_align(ui_ScrWmLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWmLbl1, "Please connect to");
    lv_obj_set_style_text_font(ui_ScrWmLbl1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWmLblAP = lv_label_create(ui_ScrWiFiManager);
    lv_obj_set_width(ui_ScrWmLblAP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWmLblAP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrWmLblAP, 2);
    lv_obj_set_y(ui_ScrWmLblAP, -30);
    lv_obj_set_align(ui_ScrWmLblAP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWmLblAP, "MusicPlayerAP");
    lv_obj_set_style_text_color(ui_ScrWmLblAP, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrWmLblAP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrWmLblAP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWmLbl2 = lv_label_create(ui_ScrWiFiManager);
    lv_obj_set_width(ui_ScrWmLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWmLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScrWmLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWmLbl2, "and go to");

    ui_ScrWmLblAddress = lv_label_create(ui_ScrWiFiManager);
    lv_obj_set_width(ui_ScrWmLblAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWmLblAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrWmLblAddress, 2);
    lv_obj_set_y(ui_ScrWmLblAddress, 35);
    lv_obj_set_align(ui_ScrWmLblAddress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWmLblAddress, "192.168.4.1");
    lv_obj_set_style_text_color(ui_ScrWmLblAddress, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScrWmLblAddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrWmLblAddress, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScrWmLbl3 = lv_label_create(ui_ScrWiFiManager);
    lv_obj_set_width(ui_ScrWmLbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScrWmLbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScrWmLbl3, 5);
    lv_obj_set_y(ui_ScrWmLbl3, 70);
    lv_obj_set_align(ui_ScrWmLbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScrWmLbl3, "in your web browser to set it up. ");

}

void ui_ScrWiFiManager_screen_destroy(void)
{
    if(ui_ScrWiFiManager) lv_obj_del(ui_ScrWiFiManager);

    // NULL screen variables
    ui_ScrWiFiManager = NULL;
    ui_ScrWmLbl0 = NULL;
    ui_ScrWmLbl1 = NULL;
    ui_ScrWmLblAP = NULL;
    ui_ScrWmLbl2 = NULL;
    ui_ScrWmLblAddress = NULL;
    ui_ScrWmLbl3 = NULL;

}
