// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Web_radio_small

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_CntnrTime = NULL;
lv_obj_t * ui_LblHrs = NULL;
lv_obj_t * ui_LblMin = NULL;
lv_obj_t * ui_LblDots = NULL;
lv_obj_t * ui_LblDate = NULL;
lv_obj_t * ui_CntnrWeather = NULL;
lv_obj_t * ui_ImgDayClear = NULL;
lv_obj_t * ui_ImgCloudy = NULL;
lv_obj_t * ui_LblWeather = NULL;
lv_obj_t * ui_CntnrButtons = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_CntnrRadio = NULL;
lv_obj_t * ui_LblStation = NULL;
lv_obj_t * ui_LblCurPlaying = NULL;
lv_obj_t * ui_PnlHorLine = NULL;
lv_obj_t * ui_PnlVerLine = NULL;
lv_obj_t * ui_SldrVolume = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CntnrTime = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CntnrTime);
    lv_obj_set_height(ui_CntnrTime, 155);
    lv_obj_set_width(ui_CntnrTime, lv_pct(50));
    lv_obj_remove_flag(ui_CntnrTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblHrs = lv_label_create(ui_CntnrTime);
    lv_obj_set_width(ui_LblHrs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblHrs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblHrs, -40);
    lv_obj_set_y(ui_LblHrs, -10);
    lv_obj_set_align(ui_LblHrs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblHrs, "23");
    lv_obj_set_style_text_font(ui_LblHrs, &ui_font_Roboto_Reg_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMin = lv_label_create(ui_CntnrTime);
    lv_obj_set_width(ui_LblMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMin, 40);
    lv_obj_set_y(ui_LblMin, -10);
    lv_obj_set_align(ui_LblMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMin, "59");
    lv_obj_set_style_text_font(ui_LblMin, &ui_font_Roboto_Reg_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDots = lv_label_create(ui_CntnrTime);
    lv_obj_set_width(ui_LblDots, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDots, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDots, 0);
    lv_obj_set_y(ui_LblDots, -15);
    lv_obj_set_align(ui_LblDots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDots, ":");
    lv_obj_set_style_text_font(ui_LblDots, &ui_font_Roboto_Reg_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblDate = lv_label_create(ui_CntnrTime);
    lv_obj_set_width(ui_LblDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblDate, 0);
    lv_obj_set_y(ui_LblDate, 20);
    lv_obj_set_align(ui_LblDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblDate, "31.12.2025");
    lv_obj_set_style_text_font(ui_LblDate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CntnrWeather = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CntnrWeather);
    lv_obj_set_height(ui_CntnrWeather, 155);
    lv_obj_set_width(ui_CntnrWeather, lv_pct(50));
    lv_obj_set_align(ui_CntnrWeather, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_CntnrWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgDayClear = lv_image_create(ui_CntnrWeather);
    lv_image_set_src(ui_ImgDayClear, &ui_img_weather_icons_dovora_interactive_128px_day_clear_png);
    lv_obj_set_width(ui_ImgDayClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgDayClear, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ImgDayClear, 0);
    lv_obj_set_y(ui_ImgDayClear, -15);
    lv_obj_set_align(ui_ImgDayClear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgDayClear, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgDayClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImgDayClear, 128);

    ui_ImgCloudy = lv_image_create(ui_CntnrWeather);
    lv_image_set_src(ui_ImgCloudy, &ui_img_weather_icons_dovora_interactive_128px_cloudy_png);
    lv_obj_set_width(ui_ImgCloudy, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ImgCloudy, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ImgCloudy, 0);
    lv_obj_set_y(ui_ImgCloudy, -15);
    lv_obj_set_align(ui_ImgCloudy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImgCloudy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImgCloudy, 128);

    ui_LblWeather = lv_label_create(ui_CntnrWeather);
    lv_obj_set_width(ui_LblWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblWeather, 0);
    lv_obj_set_y(ui_LblWeather, 20);
    lv_obj_set_align(ui_LblWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblWeather, "4 - 8 / -2 - -5 °C");
    lv_obj_set_style_text_font(ui_LblWeather, &ui_font_Roboto_Reg_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CntnrButtons = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CntnrButtons);
    lv_obj_set_height(ui_CntnrButtons, 35);
    lv_obj_set_width(ui_CntnrButtons, lv_pct(100));
    lv_obj_set_x(ui_CntnrButtons, 0);
    lv_obj_set_y(ui_CntnrButtons, -5);
    lv_obj_set_align(ui_CntnrButtons, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_CntnrButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_CntnrButtons);
    lv_obj_set_height(ui_Button1, 30);
    lv_obj_set_width(ui_Button1, lv_pct(15));
    lv_obj_set_x(ui_Button1, -120);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container1 = lv_obj_create(ui_Button1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 5);
    lv_obj_set_width(ui_Container1, lv_pct(125));
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -5);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x166600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button2 = lv_button_create(ui_CntnrButtons);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_width(ui_Button2, lv_pct(15));
    lv_obj_set_x(ui_Button2, -60);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container2 = lv_obj_create(ui_Button2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 5);
    lv_obj_set_width(ui_Container2, lv_pct(125));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -5);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x166600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button3 = lv_button_create(ui_CntnrButtons);
    lv_obj_set_height(ui_Button3, 30);
    lv_obj_set_width(ui_Button3, lv_pct(15));
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container3 = lv_obj_create(ui_Button3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 5);
    lv_obj_set_width(ui_Container3, lv_pct(125));
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -5);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x166600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button4 = lv_button_create(ui_CntnrButtons);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_width(ui_Button4, lv_pct(15));
    lv_obj_set_x(ui_Button4, 60);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container4 = lv_obj_create(ui_Button4);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 5);
    lv_obj_set_width(ui_Container4, lv_pct(125));
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -5);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x166600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button5 = lv_button_create(ui_CntnrButtons);
    lv_obj_set_height(ui_Button5, 30);
    lv_obj_set_width(ui_Button5, lv_pct(15));
    lv_obj_set_x(ui_Button5, 120);
    lv_obj_set_y(ui_Button5, 0);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x737373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Button5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container5 = lv_obj_create(ui_Button5);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 5);
    lv_obj_set_width(ui_Container5, lv_pct(125));
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -5);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x166600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CntnrRadio = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CntnrRadio);
    lv_obj_set_width(ui_CntnrRadio, lv_pct(100));
    lv_obj_set_height(ui_CntnrRadio, lv_pct(40));
    lv_obj_set_x(ui_CntnrRadio, 0);
    lv_obj_set_y(ui_CntnrRadio, -40);
    lv_obj_set_align(ui_CntnrRadio, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_CntnrRadio, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblStation = lv_label_create(ui_CntnrRadio);
    lv_obj_set_width(ui_LblStation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblStation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblStation, 0);
    lv_obj_set_y(ui_LblStation, 20);
    lv_obj_set_align(ui_LblStation, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LblStation, "Radio Station");
    lv_obj_set_style_text_color(ui_LblStation, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblStation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblStation, &ui_font_Roboto_Reg_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCurPlaying = lv_label_create(ui_CntnrRadio);
    lv_obj_set_width(ui_LblCurPlaying, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblCurPlaying, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblCurPlaying, 0);
    lv_obj_set_y(ui_LblCurPlaying, 2);
    lv_obj_set_align(ui_LblCurPlaying, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LblCurPlaying, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LblCurPlaying, "Česká státní hymna");
    lv_obj_remove_flag(ui_LblCurPlaying,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_LblCurPlaying, LV_DIR_HOR);
    lv_obj_set_style_text_font(ui_LblCurPlaying, &ui_font_Roboto_Reg_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlHorLine = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_PnlHorLine, 2);
    lv_obj_set_width(ui_PnlHorLine, lv_pct(90));
    lv_obj_set_align(ui_PnlHorLine, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PnlHorLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlHorLine, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlHorLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlVerLine = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PnlVerLine, 2);
    lv_obj_set_height(ui_PnlVerLine, 130);
    lv_obj_set_x(ui_PnlVerLine, 0);
    lv_obj_set_y(ui_PnlVerLine, 20);
    lv_obj_set_align(ui_PnlVerLine, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PnlVerLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlVerLine, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlVerLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SldrVolume = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_SldrVolume, 0, 21);
    lv_slider_set_value(ui_SldrVolume, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SldrVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SldrVolume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SldrVolume, 320);
    lv_obj_set_height(ui_SldrVolume, 34);
    lv_obj_set_x(ui_SldrVolume, 320);
    lv_obj_set_y(ui_SldrVolume, 31);
    lv_obj_set_align(ui_SldrVolume, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_SldrVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SldrVolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldrVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SldrVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SldrVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SldrVolume, &ui_img_indicator_hor_small_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SldrVolume, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SldrVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SldrVolume, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldrVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SldrVolume, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SldrVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SldrVolume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SldrVolume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SldrVolume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SldrVolume,
                                                                                                 lv_obj_get_style_pad_right(ui_SldrVolume, LV_PART_MAIN) + 1, LV_PART_MAIN);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_CntnrTime = NULL;
    ui_LblHrs = NULL;
    ui_LblMin = NULL;
    ui_LblDots = NULL;
    ui_LblDate = NULL;
    ui_CntnrWeather = NULL;
    ui_ImgDayClear = NULL;
    ui_ImgCloudy = NULL;
    ui_LblWeather = NULL;
    ui_CntnrButtons = NULL;
    ui_Button1 = NULL;
    ui_Container1 = NULL;
    ui_Button2 = NULL;
    ui_Container2 = NULL;
    ui_Button3 = NULL;
    ui_Container3 = NULL;
    ui_Button4 = NULL;
    ui_Container4 = NULL;
    ui_Button5 = NULL;
    ui_Container5 = NULL;
    ui_CntnrRadio = NULL;
    ui_LblStation = NULL;
    ui_LblCurPlaying = NULL;
    ui_PnlHorLine = NULL;
    ui_PnlVerLine = NULL;
    ui_SldrVolume = NULL;

}
