// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: Web_radio_small

#include "ui.h"

lv_obj_t * ui_ScrNetworkPlayer = NULL;
// event funtions

// build funtions

void ui_ScrNetworkPlayer_screen_init(void)
{
    ui_ScrNetworkPlayer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScrNetworkPlayer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrNetworkPlayer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrNetworkPlayer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScrNetworkPlayer_screen_destroy(void)
{
    if(ui_ScrNetworkPlayer) lv_obj_del(ui_ScrNetworkPlayer);

    // NULL screen variables
    ui_ScrNetworkPlayer = NULL;

}
